apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "beans.fullname" . }}
  labels:
    {{- include "beans.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "persistentvolumeclaims"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["*"]