apiVersion: v1
kind: Service
metadata:
  name: {{ include "beans.fullname" . }}
  labels:
    {{- include "beans.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 25565
      protocol: TCP
      name: http
  selector:
    {{- include "beans.selectorLabels" . | nindent 4 }}
