apiVersion: batch/v1
kind: Job
metadata:
  name: TOBEADDED
  labels:
    purpose: beans-game
spec:
  template:
    metadata:
      labels:
        purpose: beans-game
    spec:
      priorityClassName: TOBEADDED
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: mod-download
          image: alpine
          command:
            - TOBEADDED
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: plugins
              mountPath: "/plugins"
      containers:
        - name: minecraft-server
          image: itzg/minecraft-server
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          env:
            - name: EULA
              value: "TRUE"
            - name: VERSION
              value: "1.20.6"
            - name: TYPE
              value: PAPER
            - name: MOTD
              value: Beans++
            - name: DIFFICULTY
              value: easy
            - name: ONLINE_MODE  # needed for bungeecord
              value: "FALSE"
            - name: COPY_CONFIG_DEST
              value: /data
            - name: AUTOSTOP_TIMEOUT_EST
              value: 1200
            - name: AUTOSTOP_TIMEOUT_INIT
              value: 1200
            - name: VIEW_DISTANCE
              value: 10
            - name: REMOVE_OLD_MODS
              value: "TRUE"
            - name: SPAWN_PROTECTION
              value: 0
            - name: MEMORY
              value: 2500M
            - name: USE_AIKAR_FLAGS
              value: "TRUE"
            - name: ENABLE_AUTOSTOP
              value: "TRUE"
          readinessProbe:
            exec:
              command: [ "/usr/local/bin/mc-monitor", "status", "--host", "localhost" ]
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 20
          livenessProbe:
            exec:
              command: ["/usr/local/bin/mc-monitor", "status", "--host", "localhost"]
            initialDelaySeconds: 120
            periodSeconds: 60
          resources:
            requests:
              memory: "3Gi"
              cpu: "1500m"
              ephemeral-storage: "3Gi"
            limits:
              memory: "4Gi"
              cpu: "3500m"
              ephemeral-storage: "15Gi"
          ports:
            - containerPort: 25565
          volumeMounts:
            - name: world
              mountPath: /data
            - name: plugins
              mountPath: /plugins
            - name: config
              mountPath: /config
      restartPolicy: OnFailure
      automountServiceAccountToken: false
      volumes:
        - name: world  # always keep world as volume index zero
          persistentVolumeClaim:
            claimName: TOBEADDED
        - name: config  # always keep config as volume index one
          configMap:
            name: TOBEADDED
        - name: plugins
          emptyDir: {}
