apiVersion: v1
kind: ConfigMap
metadata:
  name: beans-bungeecord
data:
  config.yml: |
    groups:
      boxhead_crafter:
      - admin
      Tomay0:
      - admin
    ip_forward: true
    listeners:
      - priorities: 
        - lobby
        motd: "Beans++"
        query_port: 25565
        host: 0.0.0.0:25565
    servers:
      lobby:
        motd: 'Beans++ lobby'
        address: ellie-lifted:25569  # i swear that wasn't intentional
        restricted: false