apiVersion: apps/v1
kind: Deployment
metadata:
  name: beans-bungeecord
spec:
  selector:
    matchLabels:
      app: beans-bungeecord
  template:
    metadata:
      labels:
        app: beans-bungeecord
    spec:
      #securityContext:
      #  runAsUser: 1000
      #  runAsGroup: 1000
      #  fsGroup: 1000
      serviceAccountName: beans-bungeecord
      containers:
        - name: bungeecord-server
          image: itzg/bungeecord
          #securityContext:
          #  allowPrivilegeEscalation: false
          #  runAsNonRoot: true
          #  seccompProfile:
          #    type: RuntimeDefault
          #  capabilities:
          #    drop:
          #    - ALL
          env:
            - name: PLUGINS
              value: https://saggyresourcepack.blob.core.windows.net/www/BeansGameManager-1.0.jar
          readinessProbe:
            exec:
              command: [ "/usr/local/bin/mc-monitor", "status", "--host", "localhost" ]
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 20
          livenessProbe:
            exec:
              command: ["/usr/local/bin/mc-monitor", "status", "--host", "localhost"]
            initialDelaySeconds: 120
            periodSeconds: 60
          resources:
            requests:
              memory: "600Mi"
              cpu: "500m"
              ephemeral-storage: "1Gi"
            limits:
              memory: "1Gi"
              cpu: "2000m"
              ephemeral-storage: "10Gi"
          ports:
            - containerPort: 25565
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: beans-bungeecord