apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: beans-bungeecord
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "persistentvolumeclaims"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: beans-bungeecord
subjects:
  - kind: ServiceAccount
    name: beans-bungeecord
roleRef:
  kind: Role
  name: beans-bungeecord
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: beans-bungeecord