apiVersion: v1
kind: Service
metadata:
  name: beans-bungeecord-test
  annotations:
    "mc-router.itzg.me/externalServerName": "test.beans.isaacirvine.me"
spec:
  selector:
    app: beans-bungeecord
  ports:
    - protocol: TCP
      port: 25565