name: Build and Release
on: 
  push:
    branches:
      - main
jobs:
  build_and_upload:
    name: Build and Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 16

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: gradle jar

      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: build/libs  # This folder should contain only the Jar file
          container_name: www
          account_name: saggyresourcepack
          sas_token: ${{ secrets.StorageSAS }}
          overwrite: 'true'
  
  helm:
    name: Helm package and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - name: helm login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: helm package
        run: helm package deployment/beans
        
      - name: helm push
        run: |
          REPO_OWNER=`echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]'`
          CHART_VERSION=$(grep 'version:' deployment/beans/Chart.yaml | tail -n1 | awk '{ print $2}')
          helm push beans-${CHART_VERSION}.tgz oci://ghcr.io/${REPO_OWNER}/charts
